--sql
CREATE TABLE IF NOT EXISTS first_table (
	id INT NOT NULL AUTO-INCREMENT,
	name VARCHAR(128) DEFAULT NULL,
	c CHAR(1) DEFAULT NULL,
	created_at DATE DEFAULT NULL,
	PRIMARY KEY (id))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 	
